# Generated by Django 6.0.4 on 2026-05-03 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "smtp_host",
                    models.CharField(default="smtp.gmail.com", max_length=255),
                ),
                ("smtp_port", models.IntegerField(default=587)),
                ("email_address", models.EmailField(blank=True, max_length=254)),
                ("email_password", models.CharField(blank=True, max_length=255)),
                ("daily_send_limit", models.IntegerField(default=50)),
                (
                    "default_tone",
                    models.CharField(
                        choices=[
                            ("professional", "Professional"),
                            ("casual", "Casual"),
                            ("direct", "Direct"),
                            ("empathetic", "Empathetic"),
                        ],
                        default="professional",
                        max_length=20,
                    ),
                ),
                ("default_offer", models.TextField(blank=True)),
                ("auto_send_enabled", models.BooleanField(default=False)),
                ("follow_ups_enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Application Setting",
                "verbose_name_plural": "Application Settings",
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="last_contacted",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="next_follow_up",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("is_reply", models.BooleanField(default=False)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="leads.lead",
                    ),
                ),
            ],
        ),
    ]
