# Generated by Django 6.0.4 on 2026-05-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_appsetting_lead_last_contacted_lead_next_follow_up_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trigger_type', models.CharField(choices=[('on_new', 'When Lead is Added'), ('on_status_change', 'When Status Changes'), ('no_reply', 'If No Reply After X Days')], default='on_new', max_length=20)),
                ('target_status', models.CharField(blank=True, choices=[('new', 'New'), ('contacted', 'Contacted'), ('replied', 'Replied'), ('proposal', 'Proposal Sent'), ('closed', 'Closed')], max_length=20)),
                ('delay_hours', models.IntegerField(default=24, help_text='Wait time before action')),
                ('ai_prompt_override', models.TextField(blank=True, help_text='Custom AI instructions for this rule')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
