# Generated by Django 6.0.4 on 2026-05-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_scraperjob_rawlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperjob',
            name='name',
            field=models.CharField(default='Untitled Session', help_text='Session name for this niche', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scraperjob',
            name='stop_requested',
            field=models.BooleanField(default=False),
        ),
    ]
