# Generated by Django 6.0.4 on 2026-05-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_scraperjob_name_scraperjob_stop_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperjob',
            name='logs',
            field=models.TextField(blank=True, default=''),
        ),
    ]
