# Generated by Django 6.0.4 on 2026-05-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="accent_color",
            field=models.CharField(default="#4F46E5", max_length=7),
        ),
        migrations.AddField(
            model_name="resume",
            name="passport_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="resumes/passports/"
            ),
        ),
    ]
